### ISSUE TITLE
Rebrand Android Testtttttt

### ISSUE THREAD

**Issue by kgarber** [kgarber/iFormAndroidMockup#1]
### Feature
Here's something we want to do
![FormBuilder - Bad Timezone](https://user-images.githubusercontent.com/7986865/61642225-2e9a0c00-ac66-11e9-825a-ad249399308c.png)

### Test Cases
- [ ] Test Case 1
- [ ] Test Case 2

### Tasks that need to be done before removal
- [ ] Find out current usage
[insert file here]
- [ ] Given 90 day notice
[insert date and link here when announced]

### Insert SQL Statement Here 
```SQL
Select * from yourColumn
```
- [ ] Run on Load
### Tasks that need to be done before removal
- [ ] Find out current usage
[insert file here]
- [ ] Given 90 day notice
[insert date and link here when announced]

### Insert SQL Statement Here 
```SQL
Select * from yourColumn
```
- [ ] Run on Load

**Comment by kgarber** [comment]
Formatting bad because of https://github.com/ZerionSoftware/Gnosiz/issues/1010  n### Feature Removal Tasks n- [ ] What is the usage? <br />- [ ] Who is using it? n- [ ] What kind of notice do we need to give?

**Comment by kgarber** [comment]
For data collector, we need to change branding.
https://github.com/kgarber/Another-Repository/issues/6Formatting bad because of https://github.com/ZerionSoftware/Gnosiz/issues/1010  n### Feature Removal Tasks n- [ ] What is the usage?  [ ] Who is using it? n- [ ] What kind of notice do we need to give?

**Comment by kgarber** [comment]
### Test this
- [ ] Testing Line 1
- [ ] Testing Line 2Formatting bad because of https://github.com/ZerionSoftware/Gnosiz/issues/1010  n### Feature Removal Tasks n- [ ] What is the usage?  [ ] Who is using it? n- [ ] What kind of notice do we need to give?

**Comment by kgarber** [comment]
### Test this
- [ ] Testing Line 1
- [ ] Testing Line 2Formatting bad because of https://github.com/ZerionSoftware/Gnosiz/issues/1010  n### Feature Removal Tasks n- [ ] What is the usage?  [ ] Who is using it? n- [ ] What kind of notice do we need to give?

**Comment by kgarber** [comment]
Formatting bad because of https://github.com/ZerionSoftware/Gnosiz/issues/1010  n### Feature Removal Tasks n- [ ] What is the usage?  [ ] Who is using it? n- [ ] What kind of notice do we need to give?

**Comment by kgarber** [comment]
### Test this
- [ ] Testing Line 1
- [ ] Testing Line 2### Test this
- [ ] First Task
- [ ] Second Task
Formatting bad because of https://github.com/ZerionSoftware/Gnosiz/issues/1010  n### Feature Removal Tasks n- [ ] What is the usage?  [ ] Who is using it? n- [ ] What kind of notice do we need to give?

**Comment by kgarber** [comment]
### Test this
- [ ] Testing Line 1
- [ ] Testing Line 2
### Test this
- [ ] First Task
- [ ] Second Task
Formatting bad because of https://github.com/ZerionSoftware/Gnosiz/issues/1010  n### Feature Removal Tasks n- [ ] What is the usage?  [ ] Who is using it? n- [ ] What kind of notice do we need to give?
